### ISSUE TITLE
facing problem while creating dataset

### ISSUE THREAD

**Issue by dDua** [mesnilgr/is13#5]
Hi

I am trying to use your code for event detection as a sequence labelling task. I looked at the atis dataset and tried to create one in same format but I get this error while train
![events_tmp pkl](https://cloud.githubusercontent.com/assets/5347217/8640029/8c7c4252-28b7-11e5-97d8-08f68a66a034.png)
ing. Could you please take a look at the pickle file attached. It just has one sentence in all training, test and validation sets for easier debugging. 

I would really appreciate your help on this. I have been trying to get this done for quite sometime.

Traceback (most recent call last):
  File "/home/ddua/workspace/RNN/examples/elman-forward.py", line 74, in <module>
    rnn.train(word_batch, label_last_word, s['clr'])
  File "/usr/local/lib/python2.7/dist-packages/Theano-0.7.0-py2.7.egg/theano/compile/function_module.py", line 615, in **call**

```
storage_map=self.fn.storage_map)
```

  File "/usr/local/lib/python2.7/dist-packages/Theano-0.7.0-py2.7.egg/theano/compile/function_module.py", line 604, in **call**
    outputs = self.fn()
IndexError: index out of bounds
Apply node that caused the error: Subtensor{int64, int64, int64}(forall_inplace,cpu,scan_fn}.1, Constant{-1}, Constant{0}, ScalarFromTensor.0)
Inputs types: [TensorType(float64, (False, True, False)), Scalar(int64), Scalar(int64), Scalar(int64)]
Inputs shapes: [(1, 1, 4), (), (), ()]
Inputs strides: [(32, 32, 8), (), (), ()]
Inputs values: [array([[[ 0.30284221,  0.21770984,  0.31160879,  0.16783916]]]), -1, 0, 5]

P.S. Please remove .png from the extension of pkl file. I couldn't attach a .pkl file in github.

Thanks a lot,
Dheeru Dua

**Comment by dDua** [comment]
I had some issue in setting the labels correctly. It works for me now.

Thanks,
Dheeru
